sudo: false

language: cpp

compiler:
    - clang++
    - g++

os:
    - osx
    - linux

branches:
    only:
        - master

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - lcov
            - cmake

before_script:
    - export CC=/usr/bin/gcc-4.8
    - export CXX=/usr/bin/g++-4.8
    - gem install coveralls-lcov
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --zerocounters

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cmake . -DBUILD_COVERAGE:BOOL=ON
    - make
    - ctest

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    # capture coverage info
    - lcov --directory . --capture --output-file coverage.info
    # filter out system and test code
    - lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info
    # debug before upload
    - lcov --list coverage.info
    # uploads to coveralls
    - coveralls-lcov coverage.info
