language: cpp

compiler:
    - clang++
    - g++

os:
    - osx
    - linux

branches:
    only:
        - master

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq fi
    - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
    - tar xf lcov_1.11.orig.tar.gz
    - sudo make -C lcov-1.11/ install
    - gem install coveralls-lcov

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq g++-4.8 fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-4.8" fi
    - g++ --version
    - lcov --version

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --zerocounters

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cmake . -DBUILD_COVERAGE:BOOL=ON
    - make
    - ctest

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    # capture coverage info
    - lcov --directory . --capture --output-file coverage.info
    # filter out system and test code
    - lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info
    # debug before upload
    - lcov --list coverage.info
    # uploads to coveralls
    - coveralls-lcov coverage.info
