language: cpp

compiler:
    - clang
    - gcc

os:
    - osx
    - linux

branches:
    only:
        - master

before_install:
    - sudo pip install cpp-coveralls

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make

after_success:
    - coveralls --exclude test --gcov-options '\\-lp'
