language: cpp

branches:
  only:
  - master

sudo: false

matrix:
    include:
        - dist: xenial
          compiler: clang
          env: INSTALL_CXX=clang++-3.5
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5', 'george-edison55-precise-backports']
                  packages: ['clang-3.5', 'lcov', 'cmake', 'cmake-data']
        - dist: xenial
          compiler: clang
          env: INSTALL_CXX=clang++-3.6
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6', 'george-edison55-precise-backports']
                  packages: ['clang-3.6', 'lcov', 'cmake', 'cmake-data']
        - dist: xenial
          compiler: gcc-5
          env: INSTALL_CXX=g++-5 INSTALL_CC=gcc-5
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
                  packages: ['g++-5', 'lcov', 'cmake', 'cmake-data']
        - dist: xenial
          compiler: gcc-9
          env: INSTALL_CXX=g++-9 INSTALL_CC=gcc-9
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
                  packages: ['g++-9', 'lcov', 'cmake', 'cmake-data']
        - os: osx
          osx_image: xcode10.1
          compiler: clang
          env: INSTALL_CXX=clang++ INSTALL_CC=clang

before_install:
    - gem install coveralls-lcov

script:
    - mkdir -p build
    - cd build
    - CC=$INSTALL_CC CXX=$INSTALL_CXX cmake ../ -DMeshIO_BUILD_COVERAGE:BOOL=ON
    - make -j4
    - ctest --output-on-failure

after_success:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null;
        brew install lcov;
      fi
    - lcov --directory test --base-directory ../include/meshio/ --capture --no-external --output-file coverage.info
    - lcov --remove coverage.info '/usr*' -o coverage.info
    - coveralls-lcov coverage.info
